# Generated by Django 4.0.2 on 2022-02-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_oscars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='polish_title',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='films',
            name='country',
            field=models.CharField(choices=[('US', 'Stany Zjednoczone'), ('GB', 'Wielka Brytania'), ('JP', 'Japonia')], default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='films',
            name='description',
            field=models.TextField(blank=True, default='Film oskarowy', max_length=500),
        ),
        migrations.AlterField(
            model_name='films',
            name='director',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='films',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters'),
        ),
        migrations.AlterField(
            model_name='films',
            name='title',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='films',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, max_length=4, null=True),
        ),
    ]
