# Generated by Django 4.0.2 on 2022-03-14 18:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_oscars', '0003_alter_films_polish_title_alter_films_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Our_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, default='')),
                ('points', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)])),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_oscars.films')),
            ],
        ),
    ]
