# Generated by Django 4.0.2 on 2022-03-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_oscars', '0004_alter_films_year_our_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Our_rating',
        ),
    ]
