# Generated by Django 4.0.2 on 2022-03-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_oscars', '0007_alter_review_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
