# Generated by Django 4.0.2 on 2022-03-17 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_oscars', '0008_alter_review_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Films',
            new_name='films',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='User',
            new_name='user',
        ),
    ]
