# Generated by Django 4.0.2 on 2022-03-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_oscars', '0010_alter_review_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='points',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, null=True),
        ),
    ]
