# Generated by Django 4.0.3 on 2022-03-22 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_oscars', '0011_alter_review_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_oscars.films')),
                ('pointsforthisfilm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_oscars.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
